//@version=6
indicator(title = '0 TOTAL3/ KRIPTO EMA 5/21 KESİSİM TARAMA', shorttitle = 'T/K-EMA_TARA', overlay = true)

// ==================== GİRDİLER ====================
grupSec = input.string(defval='1', options=['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','ÖZEL LİSTE'], title='Grup seç')
per = input.timeframe('D', title = 'TARAMA ZAMAN DİLİMİ')
gerikontrol = input.int(5, title = 'TARANACAK BAR SAYISI')

// ==================== LRC AYARLARI ====================
ustablo = input.bool(true, 'LRC Tablosu Gösterilsin mi?', group = 'LRC AYAR BÖLÜMÜ')
lrcShowLRC = input.bool(true, 'LRC GÖSTER', group = 'LRC AYAR BÖLÜMÜ')
lrcLenHigh = input.int(300, title = 'Uzunluk - High', group = 'LRC KESİŞME GİRDİLERİ')
lrcLenLow = input.int(300, title = 'Uzunluk - Low', group = 'LRC KESİŞME GİRDİLERİ')

lrcHighReg = ta.linreg(high, lrcLenHigh, 0)
lrcLowReg = ta.linreg(low, lrcLenLow, 0)
lrcUpperReg = ta.dev(high, lrcLenHigh) + lrcHighReg
lrcLowerDev = -ta.dev(low, lrcLenLow) + lrcLowReg

if lrcShowLRC
    if ta.crossover(lrcHighReg, lrcLowReg)
        label.new(bar_index, low * 0.98, 'KESİŞME', color = color.orange, textcolor = color.white, style = label.style_label_up, size = size.tiny)
    if ta.crossunder(lrcHighReg, lrcLowReg)
        label.new(bar_index, low * 0.98, 'KESİŞME', color = color.green, textcolor = color.white, style = label.style_label_up, size = size.tiny)

plot(lrcShowLRC ? lrcHighReg : na, color = color.blue, linewidth = 2, title = 'LRC High')
plot(lrcShowLRC ? lrcLowReg : na, color = color.red, linewidth = 2, title = 'LRC Low')
plot(lrcShowLRC ? lrcUpperReg : na, color = lrcUpperReg > lrcUpperReg[1] ? color.green : color.red, linewidth = 2, title = 'LRC Upper')
plot(lrcShowLRC ? lrcLowerDev : na, color = lrcLowerDev > lrcLowerDev[1] ? color.green : color.red, linewidth = 2, title = 'LRC Lower')

// ==================== EMA EĞİM HESAPLAMALARI (her timeframe için ayrı) ====================
emaShortLen = input.int(5, 'Kısa EMA', minval = 1, group = 'EMA Eğim Ayarları')
emaLongLen = input.int(21, 'Uzun EMA', minval = 1, group = 'EMA Eğim Ayarları')
showEmaLabels = input.bool(true, 'EMA 5/21 Etiketlerini Göster', group = 'EMA Eğim Ayarları')


getSlope(tf, len) =>
    emaVal = request.security(syminfo.tickerid, tf, ta.ema(close, len), barmerge.gaps_off, barmerge.lookahead_off)
    slope = emaVal - emaVal[1]
    slope > 0 ? color.rgb(16, 245, 8) : color.purple

// EMA çizgileri (mevcut chart TF için, opsiyonel)
emaShort = ta.ema(close, emaShortLen)
emaLong = ta.ema(close, emaLongLen)
plot(emaShort, color = color.rgb(16, 245, 8), linewidth = 2, title = 'EMA 5')
plot(emaLong, color = color.new(#d9d9d9, 0), linewidth = 2, title = 'EMA 21')

// ==================== EMA 5/21 SİNYAL HESAPLAMALARI ====================
emaBuySignal  = ta.crossover(emaShort, emaLong)
emaSellSignal = ta.crossunder(emaShort, emaLong)

// ==================== EMA 5/21 ETİKETLERİNİ BASTIRMA ====================
// AL Sinyali (Mumun Altında)
if showEmaLabels and emaBuySignal
    label.new(x=bar_index, y=na, text="AL", yloc=yloc.belowbar, color=color.lime, textcolor=color.black, style=label.style_label_up, size=size.tiny)

// SAT Sinyali (Mumun Üstünde - Yakın Mesafe)
if showEmaLabels and emaSellSignal
    label.new(x=bar_index, y=na, text="SAT", yloc=yloc.abovebar, color=color.red, textcolor=color.white, style=label.style_label_down, size=size.tiny)

//////////////////////////////////////////////////////////////////////////////////////////////////

///////////////////////////////////////// TARAMA AYARLARI ////////////////////////////////////////////////////////////////////////////
//ema = ta.cross(emaShort, emaLong)
//ema1 = ta.cross(emaShort, emaLong)

//ema2 = showEmaLabels and emaBuySignal

kes1 = ta.cross(lrcHighReg, lrcLowReg)
kes2 = ta.cross(lrcLowReg, lrcHighReg)

condition = ta.barssince(kes1 or kes2) < gerikontrol

//condition1 = ta.barssince(ema2) < gerikontrol



func() =>
//ÖRNEK BİR FONKSİYON AŞAĞIDA YAZILMIŞTIR. SİZ DE İSTEDİĞİNİZ KOŞULLAR İÇİN TARAMA YAZABİLİRSİNİZ.

    cond = condition
    [close, cond]

//GRUP VE TARANACAK HİSSE SAYISINI AYNI ŞEKİLDE DİLEDİĞİNİZ GİBİ ARTIRABİLİRSİNİZ.
sb1 = input.symbol(title = '1', defval = '', group = '╠═════════════ ÖZEL LİSTE ═════════════╣')
sb2 = input.symbol(title = '2', defval = '')
sb3 = input.symbol(title = '3', defval = '')
sb4 = input.symbol(title = '4', defval = '')
sb5 = input.symbol(title = '5', defval = '')
sb6 = input.symbol(title = '6', defval = '')
sb7 = input.symbol(title = '7', defval = '')
sb8 = input.symbol(title = '8', defval = '')
sb9 = input.symbol(title = '9', defval = '')
sb10 = input.symbol(title = '10', defval = '')
sb11 = input.symbol(title = '11', defval = '')
sb12 = input.symbol(title = '12', defval = '')
sb13 = input.symbol(title = '13', defval = '')
sb14 = input.symbol(title = '14', defval = '')
sb15 = input.symbol(title = '15', defval = '')
sb16 = input.symbol(title = '16', defval = '')
sb17 = input.symbol(title = '17', defval = '')
sb18 = input.symbol(title = '18', defval = '')
sb19 = input.symbol(title = '19', defval = '')
sb20 = input.symbol(title = '20', defval = '')
sb21 = input.symbol(title = '21', defval = '')
sb22 = input.symbol(title = '22', defval = '')
sb23 = input.symbol(title = '23', defval = '')
sb24 = input.symbol(title = '24', defval ='')
sb25 = input.symbol(title = '25', defval = '')
sb26 = input.symbol(title = '26', defval ='')
sb27 = input.symbol(title = '27', defval = '')
sb28 = input.symbol(title = '28', defval ='')
sb29 = input.symbol(title = '29', defval ='')
sb30 = input.symbol(title = '30', defval ='')
sb31 = input.symbol(title = '31', defval = '')
sb32 = input.symbol(title = '32', defval ='')
sb33 = input.symbol(title = '33', defval ='')
sb34 = input.symbol(title = '34', defval ='')
sb35 = input.symbol(title = '35', defval ='')
sb36 = input.symbol(title = '36', defval ='')
sb37 = input.symbol(title = '37', defval = '')
sb38 = input.symbol(title = '38', defval ='')
sb39 = input.symbol(title = '39', defval ='')
sb40 = input.symbol(title = '40', defval ='')

// Düzenlenmiş Grup 33 Sembolleri

// === GÜNCELLENMİŞ GRUP VE RASYONEL DEĞİŞKEN TANIMLAMALARI ===

// GRUP 1
u1  = grupSec == '1' ? 'CRYPTOCAP:TOTAL3/BINANCE:0GUSDT.P' : grupSec == '2' ? 'CRYPTOCAP:TOTAL3/BINANCE:ALICEUSDT.P' : grupSec == '3' ? 'CRYPTOCAP:TOTAL3/BINANCE:B2USDT.P' : grupSec == '4' ? 'CRYPTOCAP:TOTAL3/BINANCE:BSVUSDT.P' : grupSec == '5' ? 'CRYPTOCAP:TOTAL3/BINANCE:CROSSUSDT.P' : grupSec == '6' ? 'CRYPTOCAP:TOTAL3/BINANCE:EPICUSDT.P' : grupSec == '7' ? 'CRYPTOCAP:TOTAL3/BINANCE:GRASSUSDT.P' : grupSec == '8' ? 'CRYPTOCAP:TOTAL3/BINANCE:IOSTUSDT.P' : grupSec == '9' ? 'CRYPTOCAP:TOTAL3/BINANCE:LQTYUSDT.P' : grupSec == '10' ? 'CRYPTOCAP:TOTAL3/BINANCE:MUUSDT.P' : grupSec == '11' ? 'CRYPTOCAP:TOTAL3/BINANCE:PENDLEUSDT.P' : grupSec == '12' ? 'CRYPTOCAP:TOTAL3/BINANCE:REZUSDT.P' : grupSec == '13' ? 'CRYPTOCAP:TOTAL3/BINANCE:SOONUSDT.P' : grupSec == '14' ? 'CRYPTOCAP:TOTAL3/BINANCE:TNSRUSDT.P' : grupSec == '15' ? 'CRYPTOCAP:TOTAL3/BINANCE:VVVUSDT.P' : grupSec == '16' ? 'CRYPTOCAP:TOTAL3/BINANCE:ZKCUSDT.P' : grupSec == 'ÖZEL LİSTE' ? sb1 : na
u2  = grupSec == '1' ? 'CRYPTOCAP:TOTAL3/BINANCE:1000000BOBUSDT.P' : grupSec == '2' ? 'CRYPTOCAP:TOTAL3/BINANCE:ALLOUSDT.P' : grupSec == '3' ? 'CRYPTOCAP:TOTAL3/BINANCE:BABAUSDT.P' : grupSec == '4' ? 'CRYPTOCAP:TOTAL3/BINANCE:BTCDOMUSDT.P' : grupSec == '5' ? 'CRYPTOCAP:TOTAL3/BINANCE:CRVUSDT.P' : grupSec == '6' ? 'CRYPTOCAP:TOTAL3/BINANCE:ERAUSDT.P' : grupSec == '7' ? 'CRYPTOCAP:TOTAL3/BINANCE:GRIFFAINUSDT.P' : grupSec == '8' ? 'CRYPTOCAP:TOTAL3/BINANCE:IOTAUSDT.P' : grupSec == '9' ? 'CRYPTOCAP:TOTAL3/BINANCE:LSKUSDT.P' : grupSec == '10' ? 'CRYPTOCAP:TOTAL3/BINANCE:MYXUSDT.P' : grupSec == '11' ? 'CRYPTOCAP:TOTAL3/BINANCE:PENGUUSDT.P' : grupSec == '12' ? 'CRYPTOCAP:TOTAL3/BINANCE:RIFUSDT.P' : grupSec == '13' ? 'CRYPTOCAP:TOTAL3/BINANCE:SOPHUSDT.P' : grupSec == '14' ? 'CRYPTOCAP:TOTAL3/BINANCE:TONUSDT.P' : grupSec == '15' ? 'CRYPTOCAP:TOTAL3/BINANCE:WALUSDT.P' : grupSec == '16' ? 'CRYPTOCAP:TOTAL3/BINANCE:ZKPUSDT.P' : grupSec == 'ÖZEL LİSTE' ? sb2 : na
u3  = grupSec == '1' ? 'CRYPTOCAP:TOTAL3/BINANCE:1000000MOGUSDT.P' : grupSec == '2' ? 'CRYPTOCAP:TOTAL3/BINANCE:ALLUSDT.P' : grupSec == '3' ? 'CRYPTOCAP:TOTAL3/BINANCE:BABYUSDT.P' : grupSec == '4' ? 'CRYPTOCAP:TOTAL3/BINANCE:BTCUSDT.P' : grupSec == '5' ? 'CRYPTOCAP:TOTAL3/BINANCE:CRWVUSDT.P' : grupSec == '6' ? 'CRYPTOCAP:TOTAL3/BINANCE:ESPORTSUSDT.P' : grupSec == '7' ? 'CRYPTOCAP:TOTAL3/BINANCE:GRTUSDT.P' : grupSec == '8' ? 'CRYPTOCAP:TOTAL3/BINANCE:IOTXUSDT.P' : grupSec == '9' ? 'CRYPTOCAP:TOTAL3/BINANCE:LTCUSDT.P' : grupSec == '10' ? 'CRYPTOCAP:TOTAL3/BINANCE:NAORISUSDT.P' : grupSec == '11' ? 'CRYPTOCAP:TOTAL3/BINANCE:PEOPLEUSDT.P' : grupSec == '12' ? 'CRYPTOCAP:TOTAL3/BINANCE:RIVERUSDT.P' : grupSec == '13' ? 'CRYPTOCAP:TOTAL3/BINANCE:SOXLUSDT.P' : grupSec == '14' ? 'CRYPTOCAP:TOTAL3/BINANCE:TOSHIUSDT.P' : grupSec == '15' ? 'CRYPTOCAP:TOTAL3/BINANCE:WAXPUSDT.P' : grupSec == '16' ? 'CRYPTOCAP:TOTAL3/BINANCE:ZKUSDT.P' : grupSec == 'ÖZEL LİSTE' ? sb3 : na
u4  = grupSec == '1' ? 'CRYPTOCAP:TOTAL3/BINANCE:1000BONKUSDT.P' : grupSec == '2' ? 'CRYPTOCAP:TOTAL3/BINANCE:ALPINEUSDT.P' : grupSec == '3' ? 'CRYPTOCAP:TOTAL3/BINANCE:BANANAS31USDT.P' : grupSec == '4' ? 'CRYPTOCAP:TOTAL3/BINANCE:BTRUSDT.P' : grupSec == '5' ? 'CRYPTOCAP:TOTAL3/BINANCE:CSCOUSDT.P' : grupSec == '6' ? 'CRYPTOCAP:TOTAL3/BINANCE:ESPUSDT.P' : grupSec == '7' ? 'CRYPTOCAP:TOTAL3/BINANCE:GTCUSDT.P' : grupSec == '8' ? 'CRYPTOCAP:TOTAL3/BINANCE:OUSDT.P' : grupSec == '9' ? 'CRYPTOCAP:TOTAL3/BINANCE:LUMIAUSDT.P' : grupSec == '10' ? 'CRYPTOCAP:TOTAL3/BINANCE:NATGASUSDT.P' : grupSec == '11' ? 'CRYPTOCAP:TOTAL3/BINANCE:PHAROSUSDT.P' : grupSec == '12' ? 'CRYPTOCAP:TOTAL3/BINANCE:RKLBUSDT.P' : grupSec == '13' ? 'CRYPTOCAP:TOTAL3/BINANCE:SPACEUSDT.P' : grupSec == '14' ? 'CRYPTOCAP:TOTAL3/BINANCE:TOWNSUSDT.P' : grupSec == '15' ? 'CRYPTOCAP:TOTAL3/BINANCE:WCTUSDT.P' : grupSec == '16' ? 'CRYPTOCAP:TOTAL3/BINANCE:ZORAUSDT.P' : grupSec == 'ÖZEL LİSTE' ? sb4 : na
u5  = grupSec == '1' ? 'CRYPTOCAP:TOTAL3/BINANCE:1000CATUSDT.P' : grupSec == '2' ? 'CRYPTOCAP:TOTAL3/BINANCE:ALTUSDT.P' : grupSec == '3' ? 'CRYPTOCAP:TOTAL3/BINANCE:BANANAUSDT.P' : grupSec == '4' ? 'CRYPTOCAP:TOTAL3/BINANCE:BTWUSDT.P' : grupSec == '5' ? 'CRYPTOCAP:TOTAL3/BINANCE:CTKUSDT.P' : grupSec == '6' ? 'CRYPTOCAP:TOTAL3/BINANCE:ETCUSDT.P' : grupSec == '7' ? 'CRYPTOCAP:TOTAL3/BINANCE:GUAUSDT.P' : grupSec == '8' ? 'CRYPTOCAP:TOTAL3/BINANCE:IPUSDT.P' : grupSec == '9' ? 'CRYPTOCAP:TOTAL3/BINANCE:LUNA2USDT.P' : grupSec == '10' ? 'CRYPTOCAP:TOTAL3/BINANCE:NBISUSDT.P' : grupSec == '11' ? 'CRYPTOCAP:TOTAL3/BINANCE:PHAUSDT.P' : grupSec == '12' ? 'CRYPTOCAP:TOTAL3/BINANCE:RLCUSDT.P' : grupSec == '13' ? 'CRYPTOCAP:TOTAL3/BINANCE:SPCXUSDT.P' : grupSec == '14' ? 'CRYPTOCAP:TOTAL3/BINANCE:TRADOORUSDT.P' : grupSec == '15' ? 'CRYPTOCAP:TOTAL3/BINANCE:WDCUSDT.P' : grupSec == '16' ? 'CRYPTOCAP:TOTAL3/BINANCE:ZROUSDT.P' : grupSec == 'ÖZEL LİSTE' ? sb5 : na
u6  = grupSec == '1' ? 'CRYPTOCAP:TOTAL3/BINANCE:1000CHEEMSUSDT.P' : grupSec == '2' ? 'CRYPTOCAP:TOTAL3/BINANCE:AMDUSDT.P' : grupSec == '3' ? 'CRYPTOCAP:TOTAL3/BINANCE:BANDUSDT.P' : grupSec == '4' ? 'CRYPTOCAP:TOTAL3/BINANCE:BULLAUSDT.P' : grupSec == '5' ? 'CRYPTOCAP:TOTAL3/BINANCE:CTRUSDT.P' : grupSec == '6' ? 'CRYPTOCAP:TOTAL3/BINANCE:ETHFIUSDT.P' : grupSec == '7' ? 'CRYPTOCAP:TOTAL3/BINANCE:GUNUSDT.P' : grupSec == '8' ? 'CRYPTOCAP:TOTAL3/BINANCE:IRENUSDT.P' : grupSec == '9' ? 'CRYPTOCAP:TOTAL3/BINANCE:LYNUSDT.P' : grupSec == '10' ? 'CRYPTOCAP:TOTAL3/BINANCE:NEARUSDT.P' : grupSec == '11' ? 'CRYPTOCAP:TOTAL3/BINANCE:PIEVERSEUSDT.P' : grupSec == '12' ? 'CRYPTOCAP:TOTAL3/BINANCE:ROBOUSDT.P' : grupSec == '13' ? 'CRYPTOCAP:TOTAL3/BINANCE:SPELLUSDT.P' : grupSec == '14' ? 'CRYPTOCAP:TOTAL3/BINANCE:TRBUSDT.P' : grupSec == '15' ? 'CRYPTOCAP:TOTAL3/BINANCE:WETUSDT.P' : grupSec == '16' ? 'CRYPTOCAP:TOTAL3/BINANCE:ZRXUSDT.P' : grupSec == 'ÖZEL LİSTE' ? sb6 : na
u7  = grupSec == '1' ? 'CRYPTOCAP:TOTAL3/BINANCE:1000FLOKIUSDT.P' : grupSec == '2' ? 'CRYPTOCAP:TOTAL3/BINANCE:AMZNUSDT.P' : grupSec == '3' ? 'CRYPTOCAP:TOTAL3/BINANCE:BANKUSDT.P' : grupSec == '4' ? 'CRYPTOCAP:TOTAL3/BINANCE:BUSDT.P' : grupSec == '5' ? 'CRYPTOCAP:TOTAL3/BINANCE:CTSIUSDT.P' : grupSec == '6' ? 'CRYPTOCAP:TOTAL3/BINANCE:ETHUSDT.P' : grupSec == '7' ? 'CRYPTOCAP:TOTAL3/BINANCE:GUSDT.P' : grupSec == '8' ? 'CRYPTOCAP:TOTAL3/BINANCE:IRYSUSDT.P' : grupSec == '9' ? 'CRYPTOCAP:TOTAL3/BINANCE:MAGICUSDT.P' : grupSec == '10' ? 'CRYPTOCAP:TOTAL3/BINANCE:NEIROUSDT.P' : grupSec == '11' ? 'CRYPTOCAP:TOTAL3/BINANCE:PIPPINUSDT.P' : grupSec == '12' ? 'CRYPTOCAP:TOTAL3/BINANCE:RONINUSDT.P' : grupSec == '13' ? 'CRYPTOCAP:TOTAL3/BINANCE:SPKUSDT.P' : grupSec == '14' ? 'CRYPTOCAP:TOTAL3/BINANCE:TREEUSDT.P' : grupSec == '15' ? 'CRYPTOCAP:TOTAL3/BINANCE:WIFUSDT.P' : grupSec == '16' ? 'CRYPTOCAP:TOTAL3/BINANCE:ZRXUSDT.P' : grupSec == 'ÖZEL LİSTE' ? sb7 : na
u8  = grupSec == '1' ? 'CRYPTOCAP:TOTAL3/BINANCE:1000LUNCUSDT.P' : grupSec == '2' ? 'CRYPTOCAP:TOTAL3/BINANCE:ANIMEUSDT.P' : grupSec == '3' ? 'CRYPTOCAP:TOTAL3/BINANCE:BANUSDT.P' : grupSec == '4' ? 'CRYPTOCAP:TOTAL3/BINANCE:BZUSDT.P' : grupSec == '5' ? 'CRYPTOCAP:TOTAL3/BINANCE:CUSDT.P' : grupSec == '6' ? 'CRYPTOCAP:TOTAL3/BINANCE:ETHWUSDT.P' : grupSec == '7' ? 'CRYPTOCAP:TOTAL3/BINANCE:GWEIUSDT.P' : grupSec == '8' ? 'CRYPTOCAP:TOTAL3/BINANCE:JASMYUSDT.P' : grupSec == '9' ? 'CRYPTOCAP:TOTAL3/BINANCE:MAGMAUSDT.P' : grupSec == '10' ? 'CRYPTOCAP:TOTAL3/BINANCE:NEOUSDT.P' : grupSec == '11' ? 'CRYPTOCAP:TOTAL3/BINANCE:PIXELUSDT.P' : grupSec == '12' ? 'CRYPTOCAP:TOTAL3/BINANCE:ROSEUSDT.P' : grupSec == '13' ? 'CRYPTOCAP:TOTAL3/BINANCE:SPORTFUNUSDT.P' : grupSec == '14' ? 'CRYPTOCAP:TOTAL3/BINANCE:TRIAUSDT.P' : grupSec == '15' ? 'CRYPTOCAP:TOTAL3/BINANCE:WLDUSDT.P' : grupSec == '16' ? 'CRYPTOCAP:TOTAL3/BINANCE:ZRXUSDT.P' : grupSec == 'ÖZEL LİSTE' ? sb8 : na
u9  = grupSec == '1' ? 'CRYPTOCAP:TOTAL3/BINANCE:1000PEPEUSDT.P' : grupSec == '2' ? 'CRYPTOCAP:TOTAL3/BINANCE:ANKRUSDT.P' : grupSec == '3' ? 'CRYPTOCAP:TOTAL3/BINANCE:BARDUSDT.P' : grupSec == '4' ? 'CRYPTOCAP:TOTAL3/BINANCE:C98USDT.P' : grupSec == '5' ? 'CRYPTOCAP:TOTAL3/BINANCE:CVCUSDT.P' : grupSec == '6' ? 'CRYPTOCAP:TOTAL3/BINANCE:EULUSDT.P' : grupSec == '7' ? 'CRYPTOCAP:TOTAL3/BINANCE:HAEDALUSDT.P' : grupSec == '8' ? 'CRYPTOCAP:TOTAL3/BINANCE:JCTUSDT.P' : grupSec == '9' ? 'CRYPTOCAP:TOTAL3/BINANCE:MANAUSDT.P' : grupSec == '10' ? 'CRYPTOCAP:TOTAL3/BINANCE:NEWTUSDT.P' : grupSec == '11' ? 'CRYPTOCAP:TOTAL3/BINANCE:PLAYUSDT.P' : grupSec == '12' ? 'CRYPTOCAP:TOTAL3/BINANCE:RPLUSDT.P' : grupSec == '13' ? 'CRYPTOCAP:TOTAL3/BINANCE:SPXUSDT.P' : grupSec == '14' ? 'CRYPTOCAP:TOTAL3/BINANCE:TRUMPUSDT.P' : grupSec == '15' ? 'CRYPTOCAP:TOTAL3/BINANCE:WLFIUSDT.P' : grupSec == '16' ? 'CRYPTOCAP:TOTAL3/BINANCE:ZRXUSDT.P' : grupSec == 'ÖZEL LİSTE' ? sb9 : na
u10 = grupSec == '1' ? 'CRYPTOCAP:TOTAL3/BINANCE:1000RATSUSDT.P' : grupSec == '2' ? 'CRYPTOCAP:TOTAL3/BINANCE:ANTHROPICUSDT.P' : grupSec == '3' ? 'CRYPTOCAP:TOTAL3/BINANCE:BASEDUSDT.P' : grupSec == '4' ? 'CRYPTOCAP:TOTAL3/BINANCE:CAKEUSDT.P' : grupSec == '5' ? 'CRYPTOCAP:TOTAL3/BINANCE:CVXUSDT.P' : grupSec == '6' ? 'CRYPTOCAP:TOTAL3/BINANCE:EVAAUSDT.P' : grupSec == '7' ? 'CRYPTOCAP:TOTAL3/BINANCE:HANAUSDT.P' : grupSec == '8' ? 'CRYPTOCAP:TOTAL3/BINANCE:JELLYJELLYUSDT.P' : grupSec == '9' ? 'CRYPTOCAP:TOTAL3/BINANCE:MANTAUSDT.P' : grupSec == '10' ? 'CRYPTOCAP:TOTAL3/BINANCE:NFPUSDT.P' : grupSec == '11' ? 'CRYPTOCAP:TOTAL3/BINANCE:PLTRUSDT.P' : grupSec == '12' ? 'CRYPTOCAP:TOTAL3/BINANCE:RSRUSDT.P' : grupSec == '13' ? 'CRYPTOCAP:TOTAL3/BINANCE:SPYUSDT.P' : grupSec == '14' ? 'CRYPTOCAP:TOTAL3/BINANCE:TRUSTUSDT.P' : grupSec == '15' ? 'CRYPTOCAP:TOTAL3/BINANCE:WMTUSDT.P' : grupSec == '16' ? 'CRYPTOCAP:TOTAL3/BINANCE:ZRXUSDT.P' : grupSec == 'ÖZEL LİSTE' ? sb10 : na
u11 = grupSec == '1' ? 'CRYPTOCAP:TOTAL3/BINANCE:1000SATSUSDT.P' : grupSec == '2' ? 'CRYPTOCAP:TOTAL3/BINANCE:APEUSDT.P' : grupSec == '3' ? 'CRYPTOCAP:TOTAL3/BINANCE:BASUSDT.P' : grupSec == '4' ? 'CRYPTOCAP:TOTAL3/BINANCE:CARVUSDT.P' : grupSec == '5' ? 'CRYPTOCAP:TOTAL3/BINANCE:CYBERUSDT.P' : grupSec == '6' ? 'CRYPTOCAP:TOTAL3/BINANCE:EWJUSDT.P' : grupSec == '7' ? 'CRYPTOCAP:TOTAL3/BINANCE:HBARUSDT.P' : grupSec == '8' ? 'CRYPTOCAP:TOTAL3/BINANCE:JOEUSDT.P' : grupSec == '9' ? 'CRYPTOCAP:TOTAL3/BINANCE:MANTRAUSDT.P' : grupSec == '10' ? 'CRYPTOCAP:TOTAL3/BINANCE:NIGHTUSDT.P' : grupSec == '11' ? 'CRYPTOCAP:TOTAL3/BINANCE:PLUMEUSDT.P' : grupSec == '12' ? 'CRYPTOCAP:TOTAL3/BINANCE:RUNEUSDT.P' : grupSec == '13' ? 'CRYPTOCAP:TOTAL3/BINANCE:SQDUSDT.P' : grupSec == '14' ? 'CRYPTOCAP:TOTAL3/BINANCE:TRUTHUSDT.P' : grupSec == '15' ? 'CRYPTOCAP:TOTAL3/BINANCE:WOOUSDT.P' : grupSec == '16' ? 'CRYPTOCAP:TOTAL3/BINANCE:ZRXUSDT.P' : grupSec == 'ÖZEL LİSTE' ? sb11 : na
u12 = grupSec == '1' ? 'CRYPTOCAP:TOTAL3/BINANCE:1000SHIBUSDT.P' : grupSec == '2' ? 'CRYPTOCAP:TOTAL3/BINANCE:API3USDT.P' : grupSec == '3' ? 'CRYPTOCAP:TOTAL3/BINANCE:BATUSDT.P' : grupSec == '4' ? 'CRYPTOCAP:TOTAL3/BINANCE:CATIUSDT.P' : grupSec == '5' ? 'CRYPTOCAP:TOTAL3/BINANCE:CYSUSDT.P' : grupSec == '6' ? 'CRYPTOCAP:TOTAL3/BINANCE:EWTUSDT.P' : grupSec == '7' ? 'CRYPTOCAP:TOTAL3/BINANCE:HDUSDT.P' : grupSec == '8' ? 'CRYPTOCAP:TOTAL3/BINANCE:JPMUSDT.P' : grupSec == '9' ? 'CRYPTOCAP:TOTAL3/BINANCE:MASKUSDT.P' : grupSec == '10' ? 'CRYPTOCAP:TOTAL3/BINANCE:NILUSDT.P' : grupSec == '11' ? 'CRYPTOCAP:TOTAL3/BINANCE:PNUTUSDT.P' : grupSec == '12' ? 'CRYPTOCAP:TOTAL3/BINANCE:RVNUSDT.P' : grupSec == '13' ? 'CRYPTOCAP:TOTAL3/BINANCE:SSVUSDT.P' : grupSec == '14' ? 'CRYPTOCAP:TOTAL3/BINANCE:TRXUSDT.P' : grupSec == '15' ? 'CRYPTOCAP:TOTAL3/BINANCE:WOTAMALAILIAOUSDT.P' : grupSec == '16' ? 'CRYPTOCAP:TOTAL3/BINANCE:ZRXUSDT.P' : grupSec == 'ÖZEL LİSTE' ? sb12 : na
u13 = grupSec == '1' ? 'CRYPTOCAP:TOTAL3/BINANCE:1000XECUSDT.P' : grupSec == '2' ? 'CRYPTOCAP:TOTAL3/BINANCE:APRUSDT.P' : grupSec == '3' ? 'CRYPTOCAP:TOTAL3/BINANCE:BBUSDT.P' : grupSec == '4' ? 'CRYPTOCAP:TOTAL3/BINANCE:CBRSUSDT.P' : grupSec == '5' ? 'CRYPTOCAP:TOTAL3/BINANCE:DASHUSDT.P' : grupSec == '6' ? 'CRYPTOCAP:TOTAL3/BINANCE:EWYUSDT.P' : grupSec == '7' ? 'CRYPTOCAP:TOTAL3/BINANCE:HEIUSDT.P' : grupSec == '8' ? 'CRYPTOCAP:TOTAL3/BINANCE:JSTUSDT.P' : grupSec == '9' ? 'CRYPTOCAP:TOTAL3/BINANCE:MAVIAUSDT.P' : grupSec == '10' ? 'CRYPTOCAP:TOTAL3/BINANCE:NMRUSDT.P' : grupSec == '11' ? 'CRYPTOCAP:TOTAL3/BINANCE:POLUSDT.P' : grupSec == '12' ? 'CRYPTOCAP:TOTAL3/BINANCE:SAFEUSDT.P' : grupSec == '13' ? 'CRYPTOCAP:TOTAL3/BINANCE:STABLEUSDT.P' : grupSec == '14' ? 'CRYPTOCAP:TOTAL3/BINANCE:TSLAUSDT.P' : grupSec == '15' ? 'CRYPTOCAP:TOTAL3/BINANCE:WUSDT.P' : grupSec == '16' ? 'CRYPTOCAP:TOTAL3/BINANCE:ZRXUSDT.P' : grupSec == 'ÖZEL LİSTE' ? sb13 : na
u14 = grupSec == '1' ? 'CRYPTOCAP:TOTAL3/BINANCE:1INCHUSDT.P' : grupSec == '2' ? 'CRYPTOCAP:TOTAL3/BINANCE:APTUSDT.P' : grupSec == '3' ? 'CRYPTOCAP:TOTAL3/BINANCE:BBXUSDT.P' : grupSec == '4' ? 'CRYPTOCAP:TOTAL3/BINANCE:CCUSDT.P' : grupSec == '5' ? 'CRYPTOCAP:TOTAL3/BINANCE:DEEPUSDT.P' : grupSec == '6' ? 'CRYPTOCAP:TOTAL3/BINANCE:FARTCOINUSDT.P' : grupSec == '7' ? 'CRYPTOCAP:TOTAL3/BINANCE:HEMIUSDT.P' : grupSec == '8' ? 'CRYPTOCAP:TOTAL3/BINANCE:JTOUSDT.P' : grupSec == '9' ? 'CRYPTOCAP:TOTAL3/BINANCE:MAVUSDT.P' : grupSec == '10' ? 'CRYPTOCAP:TOTAL3/BINANCE:NOKUSDT.P' : grupSec == '11' ? 'CRYPTOCAP:TOTAL3/BINANCE:POLYXUSDT.P' : grupSec == '12' ? 'CRYPTOCAP:TOTAL3/BINANCE:SAGAUSDT.P' : grupSec == '13' ? 'CRYPTOCAP:TOTAL3/BINANCE:STARUSDT.P' : grupSec == '14' ? 'CRYPTOCAP:TOTAL3/BINANCE:TSMUSDT.P' : grupSec == '15' ? 'CRYPTOCAP:TOTAL3/BINANCE:XAGUSDT.P' : grupSec == '16' ? 'CRYPTOCAP:TOTAL3/BINANCE:ZRXUSDT.P' : grupSec == 'ÖZEL LİSTE' ? sb14 : na
u15 = grupSec == '1' ? 'CRYPTOCAP:TOTAL3/BINANCE:1MBABYDOGEUSDT.P' : grupSec == '2' ? 'CRYPTOCAP:TOTAL3/BINANCE:ARBUSDT.P' : grupSec == '3' ? 'CRYPTOCAP:TOTAL3/BINANCE:BCHUSDT.P' : grupSec == '4' ? 'CRYPTOCAP:TOTAL3/BINANCE:CELOUSDT.P' : grupSec == '5' ? 'CRYPTOCAP:TOTAL3/BINANCE:DELLUSDT.P' : grupSec == '6' ? 'CRYPTOCAP:TOTAL3/BINANCE:FETUSDT.P' : grupSec == '7' ? 'CRYPTOCAP:TOTAL3/BINANCE:HFTUSDT.P' : grupSec == '8' ? 'CRYPTOCAP:TOTAL3/BINANCE:JUPUSDT.P' : grupSec == '9' ? 'CRYPTOCAP:TOTAL3/BINANCE:MBOXUSDT.P' : grupSec == '10' ? 'CRYPTOCAP:TOTAL3/BINANCE:NOMUSDT.P' : grupSec == '11' ? 'CRYPTOCAP:TOTAL3/BINANCE:POPCATUSDT.P' : grupSec == '12' ? 'CRYPTOCAP:TOTAL3/BINANCE:SAHARAUSDT.P' : grupSec == '13' ? 'CRYPTOCAP:TOTAL3/BINANCE:STBLUSDT.P' : grupSec == '14' ? 'CRYPTOCAP:TOTAL3/BINANCE:TSTUSDT.P' : grupSec == '15' ? 'CRYPTOCAP:TOTAL3/BINANCE:XAIUSDT.P' : grupSec == '16' ? 'CRYPTOCAP:TOTAL3/BINANCE:ZRXUSDT.P' : grupSec == 'ÖZEL LİSTE' ? sb15 : na
u16 = grupSec == '1' ? 'CRYPTOCAP:TOTAL3/BINANCE:2ZUSDT.P' : grupSec == '2' ? 'CRYPTOCAP:TOTAL3/BINANCE:ARCUSDT.P' : grupSec == '3' ? 'CRYPTOCAP:TOTAL3/BINANCE:BEAMXUSDT.P' : grupSec == '4' ? 'CRYPTOCAP:TOTAL3/BINANCE:CELRUSDT.P' : grupSec == '5' ? 'CRYPTOCAP:TOTAL3/BINANCE:DEXEUSDT.P' : grupSec == '6' ? 'CRYPTOCAP:TOTAL3/BINANCE:FFUSDT.P' : grupSec == '7' ? 'CRYPTOCAP:TOTAL3/BINANCE:HIGHUSDT.P' : grupSec == '8' ? 'CRYPTOCAP:TOTAL3/BINANCE:KAIAUSDT.P' : grupSec == '9' ? 'CRYPTOCAP:TOTAL3/BINANCE:MEGAUSDT.P' : grupSec == '10' ? 'CRYPTOCAP:TOTAL3/BINANCE:NOTUSDT.P' : grupSec == '11' ? 'CRYPTOCAP:TOTAL3/BINANCE:PORTALUSDT.P' : grupSec == '12' ? 'CRYPTOCAP:TOTAL3/BINANCE:SAMSUNGUSDT.P' : grupSec == '13' ? 'CRYPTOCAP:TOTAL3/BINANCE:STEEMUSDT.P' : grupSec == '14' ? 'CRYPTOCAP:TOTAL3/BINANCE:TURBOUSDT.P' : grupSec == '15' ? 'CRYPTOCAP:TOTAL3/BINANCE:XANUSDT.P' : grupSec == '16' ? 'CRYPTOCAP:TOTAL3/BINANCE:ZRXUSDT.P' : grupSec == 'ÖZEL LİSTE' ? sb16 : na
u17 = grupSec == '1' ? 'CRYPTOCAP:TOTAL3/BINANCE:4USDT.P' : grupSec == '2' ? 'CRYPTOCAP:TOTAL3/BINANCE:ARIAUSDT.P' : grupSec == '3' ? 'CRYPTOCAP:TOTAL3/BINANCE:BEATUSDT.P' : grupSec == '4' ? 'CRYPTOCAP:TOTAL3/BINANCE:CETUSUSDT.P' : grupSec == '5' ? 'CRYPTOCAP:TOTAL3/BINANCE:DIAUSDT.P' : grupSec == '6' ? 'CRYPTOCAP:TOTAL3/BINANCE:FHEUSDT.P' : grupSec == '7' ? 'CRYPTOCAP:TOTAL3/BINANCE:HIVEUSDT.P' : grupSec == '8' ? 'CRYPTOCAP:TOTAL3/BINANCE:KAITOUSDT.P' : grupSec == '9' ? 'CRYPTOCAP:TOTAL3/BINANCE:MELANIAUSDT.P' : grupSec == '10' ? 'CRYPTOCAP:TOTAL3/BINANCE:NOWUSDT.P' : grupSec == '11' ? 'CRYPTOCAP:TOTAL3/BINANCE:POWERUSDT.P' : grupSec == '12' ? 'CRYPTOCAP:TOTAL3/BINANCE:SANDUSDT.P' : grupSec == '13' ? 'CRYPTOCAP:TOTAL3/BINANCE:STGUSDT.P' : grupSec == '14' ? 'CRYPTOCAP:TOTAL3/BINANCE:TURTLEUSDT.P' : grupSec == '15' ? 'CRYPTOCAP:TOTAL3/BINANCE:XAUTUSDT.P' : grupSec == '16' ? 'CRYPTOCAP:TOTAL3/BINANCE:ZRXUSDT.P' : grupSec == 'ÖZEL LİSTE' ? sb17 : na
u18 = grupSec == '1' ? 'CRYPTOCAP:TOTAL3/BINANCE:AAPLUSDT.P' : grupSec == '2' ? 'CRYPTOCAP:TOTAL3/BINANCE:ARKMUSDT.P' : grupSec == '3' ? 'CRYPTOCAP:TOTAL3/BINANCE:BELUSDT.P' : grupSec == '4' ? 'CRYPTOCAP:TOTAL3/BINANCE:CFGUSDT.P' : grupSec == '5' ? 'CRYPTOCAP:TOTAL3/BINANCE:DISUSDT.P' : grupSec == '6' ? 'CRYPTOCAP:TOTAL3/BINANCE:FIDAUSDT.P' : grupSec == '7' ? 'CRYPTOCAP:TOTAL3/BINANCE:HMSTRUSDT.P' : grupSec == '8' ? 'CRYPTOCAP:TOTAL3/BINANCE:KASUSDT.P' : grupSec == '9' ? 'CRYPTOCAP:TOTAL3/BINANCE:MEMEUSDT.P' : grupSec == '10' ? 'CRYPTOCAP:TOTAL3/BINANCE:NVDAUSDT.P' : grupSec == '11' ? 'CRYPTOCAP:TOTAL3/BINANCE:POWRUSDT.P' : grupSec == '12' ? 'CRYPTOCAP:TOTAL3/BINANCE:SANTOSUSDT.P' : grupSec == '13' ? 'CRYPTOCAP:TOTAL3/BINANCE:STORJUSDT.P' : grupSec == '14' ? 'CRYPTOCAP:TOTAL3/BINANCE:TUSDT.P' : grupSec == '15' ? 'CRYPTOCAP:TOTAL3/BINANCE:XAUUSDT.P' : grupSec == '16' ? 'CRYPTOCAP:TOTAL3/BINANCE:ZRXUSDT.P' : grupSec == 'ÖZEL LİSTE' ? sb18 : na
u19 = grupSec == '1' ? 'CRYPTOCAP:TOTAL3/BINANCE:AAVEUSDT.P' : grupSec == '2' ? 'CRYPTOCAP:TOTAL3/BINANCE:ARKUSDT.P' : grupSec == '3' ? 'CRYPTOCAP:TOTAL3/BINANCE:BERAUSDT.P' : grupSec == '4' ? 'CRYPTOCAP:TOTAL3/BINANCE:CFXUSDT.P' : grupSec == '5' ? 'CRYPTOCAP:TOTAL3/BINANCE:DODOXUSDT.P' : grupSec == '6' ? 'CRYPTOCAP:TOTAL3/BINANCE:FIGHTUSDT.P' : grupSec == '7' ? 'CRYPTOCAP:TOTAL3/BINANCE:HOLOUSDT.P' : grupSec == '8' ? 'CRYPTOCAP:TOTAL3/BINANCE:KATUSDT.P' : grupSec == '9' ? 'CRYPTOCAP:TOTAL3/BINANCE:MERLUSDT.P' : grupSec == '10' ? 'CRYPTOCAP:TOTAL3/BINANCE:NVOUSDT.P' : grupSec == '11' ? 'CRYPTOCAP:TOTAL3/BINANCE:PRLUSDT.P' : grupSec == '12' ? 'CRYPTOCAP:TOTAL3/BINANCE:SAPIENUSDT.P' : grupSec == '13' ? 'CRYPTOCAP:TOTAL3/BINANCE:STOUSDT.P' : grupSec == '14' ? 'CRYPTOCAP:TOTAL3/BINANCE:TUTUSDT.P' : grupSec == '15' ? 'CRYPTOCAP:TOTAL3/BINANCE:XLMUSDT.P' : grupSec == '16' ? 'CRYPTOCAP:TOTAL3/BINANCE:ZRXUSDT.P' : grupSec == 'ÖZEL LİSTE' ? sb19 : na
u20 = grupSec == '1' ? 'CRYPTOCAP:TOTAL3/BINANCE:ACEUSDT.P' : grupSec == '2' ? 'CRYPTOCAP:TOTAL3/BINANCE:ARMUSDT.P' : grupSec == '3' ? 'CRYPTOCAP:TOTAL3/BINANCE:BEUSDT.P' : grupSec == '4' ? 'CRYPTOCAP:TOTAL3/BINANCE:CGPTUSDT.P' : grupSec == '5' ? 'CRYPTOCAP:TOTAL3/BINANCE:DOGEUSDT.P' : grupSec == '6' ? 'CRYPTOCAP:TOTAL3/BINANCE:FILUSDT.P' : grupSec == '7' ? 'CRYPTOCAP:TOTAL3/BINANCE:HOMEUSDT.P' : grupSec == '8' ? 'CRYPTOCAP:TOTAL3/BINANCE:KAVAUSDT.P' : grupSec == '9' ? 'CRYPTOCAP:TOTAL3/BINANCE:METAUSDT.P' : grupSec == '10' ? 'CRYPTOCAP:TOTAL3/BINANCE:NXPCUSDT.P' : grupSec == '11' ? 'CRYPTOCAP:TOTAL3/BINANCE:PROMPTUSDT.P' : grupSec == '12' ? 'CRYPTOCAP:TOTAL3/BINANCE:SCRTUSDT.P' : grupSec == '13' ? 'CRYPTOCAP:TOTAL3/BINANCE:STRKUSDT.P' : grupSec == '14' ? 'CRYPTOCAP:TOTAL3/BINANCE:TWTUSDT.P' : grupSec == '15' ? 'CRYPTOCAP:TOTAL3/BINANCE:XMRUSDT.P' : grupSec == '16' ? 'CRYPTOCAP:TOTAL3/BINANCE:ZRXUSDT.P' : grupSec == 'ÖZEL LİSTE' ? sb20 : na
u21 = grupSec == '1' ? 'CRYPTOCAP:TOTAL3/BINANCE:ACHUSDT.P' : grupSec == '2' ? 'CRYPTOCAP:TOTAL3/BINANCE:ARPAUSDT.P' : grupSec == '3' ? 'CRYPTOCAP:TOTAL3/BINANCE:BIANRENSHENGUSDT.P' : grupSec == '4' ? 'CRYPTOCAP:TOTAL3/BINANCE:CHILLGUYUSDT.P' : grupSec == '5' ? 'CRYPTOCAP:TOTAL3/BINANCE:DOGSUSDT.P' : grupSec == '6' ? 'CRYPTOCAP:TOTAL3/BINANCE:FLNCUSDT.P' : grupSec == '7' ? 'CRYPTOCAP:TOTAL3/BINANCE:HOODUSDT.P' : grupSec == '8' ? 'CRYPTOCAP:TOTAL3/BINANCE:KERNELUSDT.P' : grupSec == '9' ? 'CRYPTOCAP:TOTAL3/BINANCE:METISUSDT.P' : grupSec == '10' ? 'CRYPTOCAP:TOTAL3/BINANCE:OGNUSDT.P' : grupSec == '11' ? 'CRYPTOCAP:TOTAL3/BINANCE:PROMUSDT.P' : grupSec == '12' ? 'CRYPTOCAP:TOTAL3/BINANCE:SCRUSDT.P' : grupSec == '13' ? 'CRYPTOCAP:TOTAL3/BINANCE:STXUSDT.P' : grupSec == '14' ? 'CRYPTOCAP:TOTAL3/BINANCE:UAIUSDT.P' : grupSec == '15' ? 'CRYPTOCAP:TOTAL3/BINANCE:XNYUSDT.P' : grupSec == '16' ? 'CRYPTOCAP:TOTAL3/BINANCE:ZRXUSDT.P' : grupSec == 'ÖZEL LİSTE' ? sb21 : na
u22 = grupSec == '1' ? 'CRYPTOCAP:TOTAL3/BINANCE:ACTUSDT.P' : grupSec == '2' ? 'CRYPTOCAP:TOTAL3/BINANCE:ARUSDT.P' : grupSec == '3' ? 'CRYPTOCAP:TOTAL3/BINANCE:BICOUSDT.P' : grupSec == '4' ? 'CRYPTOCAP:TOTAL3/BINANCE:CHIPUSDT.P' : grupSec == '5' ? 'CRYPTOCAP:TOTAL3/BINANCE:DOLOUSDT.P' : grupSec == '6' ? 'CRYPTOCAP:TOTAL3/BINANCE:FLOCKUSDT.P' : grupSec == '7' ? 'CRYPTOCAP:TOTAL3/BINANCE:HOTUSDT.P' : grupSec == '8' ? 'CRYPTOCAP:TOTAL3/BINANCE:KGENUSDT.P' : grupSec == '9' ? 'CRYPTOCAP:TOTAL3/BINANCE:METUSDT.P' : grupSec == '10' ? 'CRYPTOCAP:TOTAL3/BINANCE:OGUSDT.P' : grupSec == '11' ? 'CRYPTOCAP:TOTAL3/BINANCE:PROVEUSDT.P' : grupSec == '12' ? 'CRYPTOCAP:TOTAL3/BINANCE:SEIUSDT.P' : grupSec == '13' ? 'CRYPTOCAP:TOTAL3/BINANCE:SUIUSDT.P' : grupSec == '14' ? 'CRYPTOCAP:TOTAL3/BINANCE:UBERUSDT.P' : grupSec == '15' ? 'CRYPTOCAP:TOTAL3/BINANCE:XPDUSDT.P' : grupSec == '16' ? 'CRYPTOCAP:TOTAL3/BINANCE:ZRXUSDT.P' : grupSec == 'ÖZEL LİSTE' ? sb22 : na
u23 = grupSec == '1' ? 'CRYPTOCAP:TOTAL3/BINANCE:ACUUSDT.P' : grupSec == '2' ? 'CRYPTOCAP:TOTAL3/BINANCE:ASRUSDT.P' : grupSec == '3' ? 'CRYPTOCAP:TOTAL3/BINANCE:BIGTIMEUSDT.P' : grupSec == '4' ? 'CRYPTOCAP:TOTAL3/BINANCE:CHRUSDT.P' : grupSec == '5' ? 'CRYPTOCAP:TOTAL3/BINANCE:DOODUSDT.P' : grupSec == '6' ? 'CRYPTOCAP:TOTAL3/BINANCE:FLOWUSDT.P' : grupSec == '7' ? 'CRYPTOCAP:TOTAL3/BINANCE:HUMAUSDT.P' : grupSec == '8' ? 'CRYPTOCAP:TOTAL3/BINANCE:KITEUSDT.P' : grupSec == '9' ? 'CRYPTOCAP:TOTAL3/BINANCE:MEUSDT.P' : grupSec == '10' ? 'CRYPTOCAP:TOTAL3/BINANCE:ONDOUSDT.P' : grupSec == '11' ? 'CRYPTOCAP:TOTAL3/BINANCE:PTBUSDT.P' : grupSec == '12' ? 'CRYPTOCAP:TOTAL3/BINANCE:SENTUSDT.P' : grupSec == '13' ? 'CRYPTOCAP:TOTAL3/BINANCE:SUNUSDT.P' : grupSec == '14' ? 'CRYPTOCAP:TOTAL3/BINANCE:UBUSDT.P' : grupSec == '15' ? 'CRYPTOCAP:TOTAL3/BINANCE:XPINUSDT.P' : grupSec == '16' ? 'CRYPTOCAP:TOTAL3/BINANCE:ZRXUSDT.P' : grupSec == 'ÖZEL LİSTE' ? sb23 : na
u24 = grupSec == '1' ? 'CRYPTOCAP:TOTAL3/BINANCE:ACXUSDT.P' : grupSec == '2' ? 'CRYPTOCAP:TOTAL3/BINANCE:ASTERUSDT.P' : grupSec == '3' ? 'CRYPTOCAP:TOTAL3/BINANCE:BILLUSDT.P' : grupSec == '4' ? 'CRYPTOCAP:TOTAL3/BINANCE:CHZUSDT.P' : grupSec == '5' ? 'CRYPTOCAP:TOTAL3/BINANCE:DOTUSDT.P' : grupSec == '6' ? 'CRYPTOCAP:TOTAL3/BINANCE:FLUIDUSDT.P' : grupSec == '7' ? 'CRYPTOCAP:TOTAL3/BINANCE:HUSDT.P' : grupSec == '8' ? 'CRYPTOCAP:TOTAL3/BINANCE:KMNOUSDT.P' : grupSec == '9' ? 'CRYPTOCAP:TOTAL3/BINANCE:MEWUSDT.P' : grupSec == '10' ? 'CRYPTOCAP:TOTAL3/BINANCE:ONDSUSDT.P' : grupSec == '11' ? 'CRYPTOCAP:TOTAL3/BINANCE:PUMPBTCUSDT.P' : grupSec == '12' ? 'CRYPTOCAP:TOTAL3/BINANCE:SFPUSDT.P' : grupSec == '13' ? 'CRYPTOCAP:TOTAL3/BINANCE:SUPERUSDT.P' : grupSec == '14' ? 'CRYPTOCAP:TOTAL3/BINANCE:UMAUSDT.P' : grupSec == '15' ? 'CRYPTOCAP:TOTAL3/BINANCE:XPLUSDT.P' : grupSec == '16' ? 'CRYPTOCAP:TOTAL3/BINANCE:ZRXUSDT.P' : grupSec == 'ÖZEL LİSTE' ? sb24 : na
u25 = grupSec == '1' ? 'CRYPTOCAP:TOTAL3/BINANCE:ADAUSDT.P' : grupSec == '2' ? 'CRYPTOCAP:TOTAL3/BINANCE:ASTRUSDT.P' : grupSec == '3' ? 'CRYPTOCAP:TOTAL3/BINANCE:BIOUSDT.P' : grupSec == '4' ? 'CRYPTOCAP:TOTAL3/BINANCE:CKBUSDT.P' : grupSec == '5' ? 'CRYPTOCAP:TOTAL3/BINANCE:DRAMUSDT.P' : grupSec == '6' ? 'CRYPTOCAP:TOTAL3/BINANCE:FLUXUSDT.P' : grupSec == '7' ? 'CRYPTOCAP:TOTAL3/BINANCE:HYPERUSDT.P' : grupSec == '8' ? 'CRYPTOCAP:TOTAL3/BINANCE:KNCUSDT.P' : grupSec == '9' ? 'CRYPTOCAP:TOTAL3/BINANCE:MINAUSDT.P' : grupSec == '10' ? 'CRYPTOCAP:TOTAL3/BINANCE:ONEUSDT.P' : grupSec == '11' ? 'CRYPTOCAP:TOTAL3/BINANCE:PUMPUSDT.P' : grupSec == '12' ? 'CRYPTOCAP:TOTAL3/BINANCE:SHELLUSDT.P' : grupSec == '13' ? 'CRYPTOCAP:TOTAL3/BINANCE:SUSDT.P' : grupSec == '14' ? 'CRYPTOCAP:TOTAL3/BINANCE:UNIUSDT.P' : grupSec == '15' ? 'CRYPTOCAP:TOTAL3/BINANCE:XPTUSDT.P' : grupSec == '16' ? 'CRYPTOCAP:TOTAL3/BINANCE:ZRXUSDT.P' : grupSec == 'ÖZEL LİSTE' ? sb25 : na
u26 = grupSec == '1' ? 'CRYPTOCAP:TOTAL3/BINANCE:AERGOUSDT.P' : grupSec == '2' ? 'CRYPTOCAP:TOTAL3/BINANCE:ASTSUSDT.P' : grupSec == '3' ? 'CRYPTOCAP:TOTAL3/BINANCE:BIRBUSDT.P' : grupSec == '4' ? 'CRYPTOCAP:TOTAL3/BINANCE:CLANKERUSDT.P' : grupSec == '5' ? 'CRYPTOCAP:TOTAL3/BINANCE:DRIFTUSDT.P' : grupSec == '6' ? 'CRYPTOCAP:TOTAL3/BINANCE:FOGOUSDT.P' : grupSec == '7' ? 'CRYPTOCAP:TOTAL3/BINANCE:HYPEUSDT.P' : grupSec == '8' ? 'CRYPTOCAP:TOTAL3/BINANCE:KOMAUSDT.P' : grupSec == '9' ? 'CRYPTOCAP:TOTAL3/BINANCE:MIRAUSDT.P' : grupSec == '10' ? 'CRYPTOCAP:TOTAL3/BINANCE:ONGUSDT.P' : grupSec == '11' ? 'CRYPTOCAP:TOTAL3/BINANCE:PUNDIXUSDT.P' : grupSec == '12' ? 'CRYPTOCAP:TOTAL3/BINANCE:SIGNUSDT.P' : grupSec == '13' ? 'CRYPTOCAP:TOTAL3/BINANCE:SUSHIUSDT.P' : grupSec == '14' ? 'CRYPTOCAP:TOTAL3/BINANCE:USARUSDT.P' : grupSec == '15' ? 'CRYPTOCAP:TOTAL3/BINANCE:XRPUSDT.P' : grupSec == '16' ? 'CRYPTOCAP:TOTAL3/BINANCE:ZRXUSDT.P' : grupSec == 'ÖZEL LİSTE' ? sb26 : na
u27 = grupSec == '1' ? 'CRYPTOCAP:TOTAL3/BINANCE:AEROUSDT.P' : grupSec == '2' ? 'CRYPTOCAP:TOTAL3/BINANCE:ATHUSDT.P' : grupSec == '3' ? 'CRYPTOCAP:TOTAL3/BINANCE:BLESSUSDT.P' : grupSec == '4' ? 'CRYPTOCAP:TOTAL3/BINANCE:CLOUSDT.P' : grupSec == '5' ? 'CRYPTOCAP:TOTAL3/BINANCE:DUSDT.P' : grupSec == '6' ? 'CRYPTOCAP:TOTAL3/BINANCE:FOLKSUSDT.P' : grupSec == '7' ? 'CRYPTOCAP:TOTAL3/BINANCE:HYUNDAIUSDT.P' : grupSec == '8' ? 'CRYPTOCAP:TOTAL3/BINANCE:KSMUSDT.P' : grupSec == '9' ? 'CRYPTOCAP:TOTAL3/BINANCE:MITOUSDT.P' : grupSec == '10' ? 'CRYPTOCAP:TOTAL3/BINANCE:ONTUSDT.P' : grupSec == '11' ? 'CRYPTOCAP:TOTAL3/BINANCE:PYTHUSDT.P' : grupSec == '12' ? 'CRYPTOCAP:TOTAL3/BINANCE:SIRENUSDT.P' : grupSec == '13' ? 'CRYPTOCAP:TOTAL3/BINANCE:SWARMSUSDT.P' : grupSec == '14' ? 'CRYPTOCAP:TOTAL3/BINANCE:USDCUSDT.P' : grupSec == '15' ? 'CRYPTOCAP:TOTAL3/BINANCE:XTZUSDT.P' : grupSec == '16' ? 'CRYPTOCAP:TOTAL3/BINANCE:ZRXUSDT.P' : grupSec == 'ÖZEL LİSTE' ? sb27 : na
u28 = grupSec == '1' ? 'CRYPTOCAP:TOTAL3/BINANCE:AEVOUSDT.P' : grupSec == '2' ? 'CRYPTOCAP:TOTAL3/BINANCE:ATOMUSDT.P' : grupSec == '3' ? 'CRYPTOCAP:TOTAL3/BINANCE:BLUAIUSDT.P' : grupSec == '4' ? 'CRYPTOCAP:TOTAL3/BINANCE:CLUSDT.P' : grupSec == '5' ? 'CRYPTOCAP:TOTAL3/BINANCE:DUSKUSDT.P' : grupSec == '6' ? 'CRYPTOCAP:TOTAL3/BINANCE:FORMUSDT.P' : grupSec == '7' ? 'CRYPTOCAP:TOTAL3/BINANCE:IBMUSDT.P' : grupSec == '8' ? 'CRYPTOCAP:TOTAL3/BINANCE:LABUSDT.P' : grupSec == '9' ? 'CRYPTOCAP:TOTAL3/BINANCE:MMTUSDT.P' : grupSec == '10' ? 'CRYPTOCAP:TOTAL3/BINANCE:ONUSDT.P' : grupSec == '11' ? 'CRYPTOCAP:TOTAL3/BINANCE:QCOMUSDT.P' : grupSec == '12' ? 'CRYPTOCAP:TOTAL3/BINANCE:SKHYNIXUSDT.P' : grupSec == '13' ? 'CRYPTOCAP:TOTAL3/BINANCE:SXTUSDT.P' : grupSec == '14' ? 'CRYPTOCAP:TOTAL3/BINANCE:USELESSUSDT.P' : grupSec == '15' ? 'CRYPTOCAP:TOTAL3/BINANCE:XVGUSDT.P' : grupSec == '16' ? 'CRYPTOCAP:TOTAL3/BINANCE:ZRXUSDT.P' : grupSec == 'ÖZEL LİSTE' ? sb28 : na
u29 = grupSec == '1' ? 'CRYPTOCAP:TOTAL3/BINANCE:AGLDUSDT.P' : grupSec == '2' ? 'CRYPTOCAP:TOTAL3/BINANCE:ATUSDT.P' : grupSec == '3' ? 'CRYPTOCAP:TOTAL3/BINANCE:BLURUSDT.P' : grupSec == '4' ? 'CRYPTOCAP:TOTAL3/BINANCE:COAIUSDT.P' : grupSec == '5' ? 'CRYPTOCAP:TOTAL3/BINANCE:DYDXUSDT.P' : grupSec == '6' ? 'CRYPTOCAP:TOTAL3/BINANCE:FRAXUSDT.P' : grupSec == '7' ? 'CRYPTOCAP:TOTAL3/BINANCE:ICNTUSDT.P' : grupSec == '8' ? 'CRYPTOCAP:TOTAL3/BINANCE:LAUSDT.P' : grupSec == '9' ? 'CRYPTOCAP:TOTAL3/BINANCE:MOCAUSDT.P' : grupSec == '10' ? 'CRYPTOCAP:TOTAL3/BINANCE:OPENAIUSDT.P' : grupSec == '11' ? 'CRYPTOCAP:TOTAL3/BINANCE:QNTUSDT.P' : grupSec == '12' ? 'CRYPTOCAP:TOTAL3/BINANCE:SKLUSDT.P' : grupSec == '13' ? 'CRYPTOCAP:TOTAL3/BINANCE:SYNUSDT.P' : grupSec == '14' ? 'CRYPTOCAP:TOTAL3/BINANCE:USTCUSDT.P' : grupSec == '15' ? 'CRYPTOCAP:TOTAL3/BINANCE:XVSUSDT.P' : grupSec == '16' ? 'CRYPTOCAP:TOTAL3/BINANCE:ZRXUSDT.P' : grupSec == 'ÖZEL LİSTE' ? sb29 : na
u30 = grupSec == '1' ? 'CRYPTOCAP:TOTAL3/BINANCE:AGTUSDT.P' : grupSec == '2' ? 'CRYPTOCAP:TOTAL3/BINANCE:AUCTIONUSDT.P' : grupSec == '3' ? 'CRYPTOCAP:TOTAL3/BINANCE:BMTUSDT.P' : grupSec == '4' ? 'CRYPTOCAP:TOTAL3/BINANCE:COHRUSDT.P' : grupSec == '5' ? 'CRYPTOCAP:TOTAL3/BINANCE:DYMUSDT.P' : grupSec == '6' ? 'CRYPTOCAP:TOTAL3/BINANCE:FUSDT.P' : grupSec == '7' ? 'CRYPTOCAP:TOTAL3/BINANCE:ICPUSDT.P' : grupSec == '8' ? 'CRYPTOCAP:TOTAL3/BINANCE:LAYERUSDT.P' : grupSec == '9' ? 'CRYPTOCAP:TOTAL3/BINANCE:MONUSDT.P' : grupSec == '10' ? 'CRYPTOCAP:TOTAL3/BINANCE:OPENUSDT.P' : grupSec == '11' ? 'CRYPTOCAP:TOTAL3/BINANCE:QNTXUSDT.P' : grupSec == '12' ? 'CRYPTOCAP:TOTAL3/BINANCE:SKRUSDT.P' : grupSec == '13' ? 'CRYPTOCAP:TOTAL3/BINANCE:SYRUPUSDT.P' : grupSec == '14' ? 'CRYPTOCAP:TOTAL3/BINANCE:USUALUSDT.P' : grupSec == '15' ? 'CRYPTOCAP:TOTAL3/BINANCE:YBUSDT.P' : grupSec == '16' ? 'CRYPTOCAP:TOTAL3/BINANCE:ZRXUSDT.P' : grupSec == 'ÖZEL LİSTE' ? sb30 : na
u31 = grupSec == '1' ? 'CRYPTOCAP:TOTAL3/BINANCE:AIAUSDT.P' : grupSec == '2' ? 'CRYPTOCAP:TOTAL3/BINANCE:AUSDT.P' : grupSec == '3' ? 'CRYPTOCAP:TOTAL3/BINANCE:BNBUSDT.P' : grupSec == '4' ? 'CRYPTOCAP:TOTAL3/BINANCE:COINUSDT.P' : grupSec == '5' ? 'CRYPTOCAP:TOTAL3/BINANCE:EDENUSDT.P' : grupSec == '6' ? 'CRYPTOCAP:TOTAL3/BINANCE:GALAUSDT.P' : grupSec == '7' ? 'CRYPTOCAP:TOTAL3/BINANCE:ICXUSDT.P' : grupSec == '8' ? 'CRYPTOCAP:TOTAL3/BINANCE:LDOUSDT.P' : grupSec == '9' ? 'CRYPTOCAP:TOTAL3/BINANCE:MOODENGUSDT.P' : grupSec == '10' ? 'CRYPTOCAP:TOTAL3/BINANCE:OPGUSDT.P' : grupSec == '11' ? 'CRYPTOCAP:TOTAL3/BINANCE:QQQUSDT.P' : grupSec == '12' ? 'CRYPTOCAP:TOTAL3/BINANCE:SKYAIUSDT.P' : grupSec == '13' ? 'CRYPTOCAP:TOTAL3/BINANCE:TACUSDT.P' : grupSec == '14' ? 'CRYPTOCAP:TOTAL3/BINANCE:USUSDT.P' : grupSec == '15' ? 'CRYPTOCAP:TOTAL3/BINANCE:YFIUSDT.P' : grupSec == '16' ? 'CRYPTOCAP:TOTAL3/BINANCE:ZRXUSDT.P' : grupSec == 'ÖZEL LİSTE' ? sb31 : na
u32 = grupSec == '1' ? 'CRYPTOCAP:TOTAL3/BINANCE:AIGENSYNUSDT.P' : grupSec == '2' ? 'CRYPTOCAP:TOTAL3/BINANCE:AVAAIUSDT.P' : grupSec == '3' ? 'CRYPTOCAP:TOTAL3/BINANCE:BNTUSDT.P' : grupSec == '4' ? 'CRYPTOCAP:TOTAL3/BINANCE:COLLECTUSDT.P' : grupSec == '5' ? 'CRYPTOCAP:TOTAL3/BINANCE:EDGEUSDT.P' : grupSec == '6' ? 'CRYPTOCAP:TOTAL3/BINANCE:GASUSDT.P' : grupSec == '7' ? 'CRYPTOCAP:TOTAL3/BINANCE:IDOLUSDT.P' : grupSec == '8' ? 'CRYPTOCAP:TOTAL3/BINANCE:LIGHTUSDT.P' : grupSec == '9' ? 'CRYPTOCAP:TOTAL3/BINANCE:MORPHOUSDT.P' : grupSec == '10' ? 'CRYPTOCAP:TOTAL3/BINANCE:OPNUSDT.P' : grupSec == '11' ? 'CRYPTOCAP:TOTAL3/BINANCE:QTUMUSDT.P' : grupSec == '12' ? 'CRYPTOCAP:TOTAL3/BINANCE:SKYUSDT.P' : grupSec == '13' ? 'CRYPTOCAP:TOTAL3/BINANCE:TAGUSDT.P' : grupSec == '14' ? 'CRYPTOCAP:TOTAL3/BINANCE:VANAUSDT.P' : grupSec == '15' ? 'CRYPTOCAP:TOTAL3/BINANCE:YGGUSDT.P' : grupSec == '16' ? 'CRYPTOCAP:TOTAL3/BINANCE:ZRXUSDT.P' : grupSec == 'ÖZEL LİSTE' ? sb32 : na
u33 = grupSec == '1' ? 'CRYPTOCAP:TOTAL3/BINANCE:AINUSDT.P' : grupSec == '2' ? 'CRYPTOCAP:TOTAL3/BINANCE:AVAUSDT.P' : grupSec == '3' ? 'CRYPTOCAP:TOTAL3/BINANCE:BOMEUSDT.P' : grupSec == '4' ? 'CRYPTOCAP:TOTAL3/BINANCE:COMPUSDT.P' : grupSec == '5' ? 'CRYPTOCAP:TOTAL3/BINANCE:EDUUSDT.P' : grupSec == '6' ? 'CRYPTOCAP:TOTAL3/BINANCE:GENIUSUSDT.P' : grupSec == '7' ? 'CRYPTOCAP:TOTAL3/BINANCE:IDUSDT.P' : grupSec == '8' ? 'CRYPTOCAP:TOTAL3/BINANCE:LINEAUSDT.P' : grupSec == '9' ? 'CRYPTOCAP:TOTAL3/BINANCE:MOVEUSDT.P' : grupSec == '10' ? 'CRYPTOCAP:TOTAL3/BINANCE:OPUSDT.P' : grupSec == '11' ? 'CRYPTOCAP:TOTAL3/BINANCE:QUSDT.P' : grupSec == '12' ? 'CRYPTOCAP:TOTAL3/BINANCE:SLPUSDT.P' : grupSec == '13' ? 'CRYPTOCAP:TOTAL3/BINANCE:TAIKOUSDT.P' : grupSec == '14' ? 'CRYPTOCAP:TOTAL3/BINANCE:VANRYUSDT.P' : grupSec == '15' ? 'CRYPTOCAP:TOTAL3/BINANCE:ZAMAUSDT.P' : grupSec == '16' ? 'CRYPTOCAP:TOTAL3/BINANCE:ZRXUSDT.P' : grupSec == 'ÖZEL LİSTE' ? sb33 : na
u34 = grupSec == '1' ? 'CRYPTOCAP:TOTAL3/BINANCE:AIOTUSDT.P' : grupSec == '2' ? 'CRYPTOCAP:TOTAL3/BINANCE:AVAXUSDT.P' : grupSec == '3' ? 'CRYPTOCAP:TOTAL3/BINANCE:BRETTUSDT.P' : grupSec == '4' ? 'CRYPTOCAP:TOTAL3/BINANCE:COOKIEUSDT.P' : grupSec == '5' ? 'CRYPTOCAP:TOTAL3/BINANCE:EGLDUSDT.P' : grupSec == '6' ? 'CRYPTOCAP:TOTAL3/BINANCE:GIGGLEUSDT.P' : grupSec == '7' ? 'CRYPTOCAP:TOTAL3/BINANCE:ILVUSDT.P' : grupSec == '8' ? 'CRYPTOCAP:TOTAL3/BINANCE:LINKUSDT.P' : grupSec == '9' ? 'CRYPTOCAP:TOTAL3/BINANCE:MOVRUSDT.P' : grupSec == '10' ? 'CRYPTOCAP:TOTAL3/BINANCE:ORCAUSDT.P' : grupSec == '11' ? 'CRYPTOCAP:TOTAL3/BINANCE:RAREUSDT.P' : grupSec == '12' ? 'CRYPTOCAP:TOTAL3/BINANCE:SLXUSDT.P' : grupSec == '13' ? 'CRYPTOCAP:TOTAL3/BINANCE:TAKEUSDT.P' : grupSec == '14' ? 'CRYPTOCAP:TOTAL3/BINANCE:VELODROMEUSDT.P' : grupSec == '15' ? 'CRYPTOCAP:TOTAL3/BINANCE:ZBTUSDT.P' : grupSec == '16' ? 'CRYPTOCAP:TOTAL3/BINANCE:ZRXUSDT.P' : grupSec == 'ÖZEL LİSTE' ? sb34 : na
u35 = grupSec == '1' ? 'CRYPTOCAP:TOTAL3/BINANCE:AIOUSDT.P' : grupSec == '2' ? 'CRYPTOCAP:TOTAL3/BINANCE:AVGOUSDT.P' : grupSec == '3' ? 'CRYPTOCAP:TOTAL3/BINANCE:BREVUSDT.P' : grupSec == '4' ? 'CRYPTOCAP:TOTAL3/BINANCE:COPPERUSDT.P' : grupSec == '5' ? 'CRYPTOCAP:TOTAL3/BINANCE:EIGENUSDT.P' : grupSec == '6' ? 'CRYPTOCAP:TOTAL3/BINANCE:GLMUSDT.P' : grupSec == '7' ? 'CRYPTOCAP:TOTAL3/BINANCE:IMXUSDT.P' : grupSec == '8' ? 'CRYPTOCAP:TOTAL3/BINANCE:LISTAUSDT.P' : grupSec == '9' ? 'CRYPTOCAP:TOTAL3/BINANCE:MRVLUSDT.P' : grupSec == '10' ? 'CRYPTOCAP:TOTAL3/BINANCE:ORCLUSDT.P' : grupSec == '11' ? 'CRYPTOCAP:TOTAL3/BINANCE:RAVEUSDT.P' : grupSec == '12' ? 'CRYPTOCAP:TOTAL3/BINANCE:SNDKUSDT.P' : grupSec == '13' ? 'CRYPTOCAP:TOTAL3/BINANCE:TAOUSDT.P' : grupSec == '14' ? 'CRYPTOCAP:TOTAL3/BINANCE:VELVETUSDT.P' : grupSec == '15' ? 'CRYPTOCAP:TOTAL3/BINANCE:ZECUSDT.P' : grupSec == '16' ? 'CRYPTOCAP:TOTAL3/BINANCE:ZRXUSDT.P' : grupSec == 'ÖZEL LİSTE' ? sb35 : na
u36 = grupSec == '1' ? 'CRYPTOCAP:TOTAL3/BINANCE:AIXBTUSDT.P' : grupSec == '2' ? 'CRYPTOCAP:TOTAL3/BINANCE:AVNTUSDT.P' : grupSec == '3' ? 'CRYPTOCAP:TOTAL3/BINANCE:BRKBUSDT.P' : grupSec == '4' ? 'CRYPTOCAP:TOTAL3/BINANCE:COSUSDT.P' : grupSec == '5' ? 'CRYPTOCAP:TOTAL3/BINANCE:ELSAUSDT.P' : grupSec == '6' ? 'CRYPTOCAP:TOTAL3/BINANCE:GMTUSDT.P' : grupSec == '7' ? 'CRYPTOCAP:TOTAL3/BINANCE:INITUSDT.P' : grupSec == '8' ? 'CRYPTOCAP:TOTAL3/BINANCE:LITEUSDT.P' : grupSec == '9' ? 'CRYPTOCAP:TOTAL3/BINANCE:MSFTUSDT.P' : grupSec == '10' ? 'CRYPTOCAP:TOTAL3/BINANCE:ORDERUSDT.P' : grupSec == '11' ? 'CRYPTOCAP:TOTAL3/BINANCE:RAYSOLUSDT.P' : grupSec == '12' ? 'CRYPTOCAP:TOTAL3/BINANCE:SNXUSDT.P' : grupSec == '13' ? 'CRYPTOCAP:TOTAL3/BINANCE:TAUSDT.P' : grupSec == '14' ? 'CRYPTOCAP:TOTAL3/BINANCE:VETUSDT.P' : grupSec == '15' ? 'CRYPTOCAP:TOTAL3/BINANCE:ZENUSDT.P' : grupSec == '16' ? 'CRYPTOCAP:TOTAL3/BINANCE:ZRXUSDT.P' : grupSec == 'ÖZEL LİSTE' ? sb36 : na
u37 = grupSec == '1' ? 'CRYPTOCAP:TOTAL3/BINANCE:AKEUSDT.P' : grupSec == '2' ? 'CRYPTOCAP:TOTAL3/BINANCE:AWEUSDT.P' : grupSec == '3' ? 'CRYPTOCAP:TOTAL3/BINANCE:BROCCOLI714USDT.P' : grupSec == '4' ? 'CRYPTOCAP:TOTAL3/BINANCE:COTIUSDT.P' : grupSec == '5' ? 'CRYPTOCAP:TOTAL3/BINANCE:ENAUSDT.P' : grupSec == '6' ? 'CRYPTOCAP:TOTAL3/BINANCE:GMXUSDT.P' : grupSec == '7' ? 'CRYPTOCAP:TOTAL3/BINANCE:INJUSDT.P' : grupSec == '8' ? 'CRYPTOCAP:TOTAL3/BINANCE:LITUSDT.P' : grupSec == '9' ? 'CRYPTOCAP:TOTAL3/BINANCE:MSTRUSDT.P' : grupSec == '10' ? 'CRYPTOCAP:TOTAL3/BINANCE:ORDIUSDT.P' : grupSec == '11' ? 'CRYPTOCAP:TOTAL3/BINANCE:RECALLUSDT.P' : grupSec == '12' ? 'CRYPTOCAP:TOTAL3/BINANCE:SOLUSDT.P' : grupSec == '13' ? 'CRYPTOCAP:TOTAL3/BINANCE:THETAUSDT.P' : grupSec == '14' ? 'CRYPTOCAP:TOTAL3/BINANCE:VICUSDT.P' : grupSec == '15' ? 'CRYPTOCAP:TOTAL3/BINANCE:ZEREBROUSDT.P' : grupSec == '16' ? 'CRYPTOCAP:TOTAL3/BINANCE:ZRXUSDT.P' : grupSec == 'ÖZEL LİSTE' ? sb37 : na
u38 = grupSec == '1' ? 'CRYPTOCAP:TOTAL3/BINANCE:AKTUSDT.P' : grupSec == '2' ? 'CRYPTOCAP:TOTAL3/BINANCE:AXLUSDT.P' : grupSec == '3' ? 'CRYPTOCAP:TOTAL3/BINANCE:BROCCOLIF3BUSDT.P' : grupSec == '4' ? 'CRYPTOCAP:TOTAL3/BINANCE:COWUSDT.P' : grupSec == '5' ? 'CRYPTOCAP:TOTAL3/BINANCE:ENJUSDT.P' : grupSec == '6' ? 'CRYPTOCAP:TOTAL3/BINANCE:GOATUSDT.P' : grupSec == '7' ? 'CRYPTOCAP:TOTAL3/BINANCE:INTCUSDT.P' : grupSec == '8' ? 'CRYPTOCAP:TOTAL3/BINANCE:LLYUSDT.P' : grupSec == '9' ? 'CRYPTOCAP:TOTAL3/BINANCE:MTLUSDT.P' : grupSec == '10' ? 'CRYPTOCAP:TOTAL3/BINANCE:PARTIUSDT.P' : grupSec == '11' ? 'CRYPTOCAP:TOTAL3/BINANCE:REDUSDT.P' : grupSec == '12' ? 'CRYPTOCAP:TOTAL3/BINANCE:SOLVUSDT.P' : grupSec == '13' ? 'CRYPTOCAP:TOTAL3/BINANCE:THEUSDT.P' : grupSec == '14' ? 'CRYPTOCAP:TOTAL3/BINANCE:VIRTUALUSDT.P' : grupSec == '15' ? 'CRYPTOCAP:TOTAL3/BINANCE:ZESTUSDT.P' : grupSec == '16' ? 'CRYPTOCAP:TOTAL3/BINANCE:ZRXUSDT.P' : grupSec == 'ÖZEL LİSTE' ? sb38 : na
u39 = grupSec == '1' ? 'CRYPTOCAP:TOTAL3/BINANCE:ALCHUSDT.P' : grupSec == '2' ? 'CRYPTOCAP:TOTAL3/BINANCE:AXSUSDT.P' : grupSec == '3' ? 'CRYPTOCAP:TOTAL3/BINANCE:BRUSDT.P' : grupSec == '4' ? 'CRYPTOCAP:TOTAL3/BINANCE:CRCLUSDT.P' : grupSec == '5' ? 'CRYPTOCAP:TOTAL3/BINANCE:ENSOUSDT.P' : grupSec == '6' ? 'CRYPTOCAP:TOTAL3/BINANCE:GOOGLUSDT.P' : grupSec == '7' ? 'CRYPTOCAP:TOTAL3/BINANCE:INUSDT.P' : grupSec == '8' ? 'CRYPTOCAP:TOTAL3/BINANCE:LONGXIAUSDT.P' : grupSec == '9' ? 'CRYPTOCAP:TOTAL3/BINANCE:MUBARAKUSDT.P' : grupSec == '10' ? 'CRYPTOCAP:TOTAL3/BINANCE:PAXGUSDT.P' : grupSec == '11' ? 'CRYPTOCAP:TOTAL3/BINANCE:RENDERUSDT.P' : grupSec == '12' ? 'CRYPTOCAP:TOTAL3/BINANCE:SOMIUSDT.P' : grupSec == '13' ? 'CRYPTOCAP:TOTAL3/BINANCE:TIAUSDT.P' : grupSec == '14' ? 'CRYPTOCAP:TOTAL3/BINANCE:VTHOUSDT.P' : grupSec == '15' ? 'CRYPTOCAP:TOTAL3/BINANCE:ZETAUSDT.P' : grupSec == '16' ? 'CRYPTOCAP:TOTAL3/BINANCE:ZRXUSDT.P' : grupSec == 'ÖZEL LİSTE' ? sb39 : na
u40 = grupSec == '1' ? 'CRYPTOCAP:TOTAL3/BINANCE:ALGOUSDT.P' : grupSec == '2' ? 'CRYPTOCAP:TOTAL3/BINANCE:AZTECUSDT.P' : grupSec == '3' ? 'CRYPTOCAP:TOTAL3/BINANCE:BSBUSDT.P' : grupSec == '4' ? 'CRYPTOCAP:TOTAL3/BINANCE:CRMUSDT.P' : grupSec == '5' ? 'CRYPTOCAP:TOTAL3/BINANCE:ENSUSDT.P' : grupSec == '6' ? 'CRYPTOCAP:TOTAL3/BINANCE:GPSUSDT.P' : grupSec == '7' ? 'CRYPTOCAP:TOTAL3/BINANCE:INXUSDT.P' : grupSec == '8' ? 'CRYPTOCAP:TOTAL3/BINANCE:LPTUSDT.P' : grupSec == '9' ? 'CRYPTOCAP:TOTAL3/BINANCE:MUSDT.P' : grupSec == '10' ? 'CRYPTOCAP:TOTAL3/BINANCE:PAYPUSDT.P' : grupSec == '11' ? 'CRYPTOCAP:TOTAL3/BINANCE:RESOLVUSDT.P' : grupSec == '12' ? 'CRYPTOCAP:TOTAL3/BINANCE:SONICUSDT.P' : grupSec == '13' ? 'CRYPTOCAP:TOTAL3/BINANCE:TLMUSDT.P' : grupSec == '14' ? 'CRYPTOCAP:TOTAL3/BINANCE:VUSDT.P' : grupSec == '15' ? 'CRYPTOCAP:TOTAL3/BINANCE:ZILUSDT.P' : grupSec == '16' ? 'CRYPTOCAP:TOTAL3/BINANCE:ZRXUSDT.P' : grupSec == 'ÖZEL LİSTE' ? sb40 : na


[v1, s1] = request.security(u1, per, func(), ignore_invalid_symbol = true)
[v2, s2] = request.security(u2, per, func(), ignore_invalid_symbol = true)
[v3, s3] = request.security(u3, per, func(), ignore_invalid_symbol = true)
[v4, s4] = request.security(u4, per, func(), ignore_invalid_symbol = true)
[v5, s5] = request.security(u5, per, func(), ignore_invalid_symbol = true)
[v6, s6] = request.security(u6, per, func(), ignore_invalid_symbol = true)
[v7, s7] = request.security(u7, per, func(), ignore_invalid_symbol = true)
[v8, s8] = request.security(u8, per, func(), ignore_invalid_symbol = true)
[v9, s9] = request.security(u9, per, func(), ignore_invalid_symbol = true)
[v10, s10] = request.security(u10, per, func(), ignore_invalid_symbol = true)
[v11, s11] = request.security(u11, per, func(), ignore_invalid_symbol = true)
[v12, s12] = request.security(u12, per, func(), ignore_invalid_symbol = true)
[v13, s13] = request.security(u13, per, func(), ignore_invalid_symbol = true)
[v14, s14] = request.security(u14, per, func(), ignore_invalid_symbol = true)
[v15, s15] = request.security(u15, per, func(), ignore_invalid_symbol = true)
[v16, s16] = request.security(u16, per, func(), ignore_invalid_symbol = true)
[v17, s17] = request.security(u17, per, func(), ignore_invalid_symbol = true)
[v18, s18] = request.security(u18, per, func(), ignore_invalid_symbol = true)
[v19, s19] = request.security(u19, per, func(), ignore_invalid_symbol = true)
[v20, s20] = request.security(u20, per, func(), ignore_invalid_symbol = true)
[v21, s21] = request.security(u21, per, func(), ignore_invalid_symbol = true)
[v22, s22] = request.security(u22, per, func(), ignore_invalid_symbol = true)
[v23, s23] = request.security(u23, per, func(), ignore_invalid_symbol = true)
[v24, s24] = request.security(u24, per, func(), ignore_invalid_symbol = true)
[v25, s25] = request.security(u25, per, func(), ignore_invalid_symbol = true)
[v26, s26] = request.security(u26, per, func(), ignore_invalid_symbol = true)
[v27, s27] = request.security(u27, per, func(), ignore_invalid_symbol = true)
[v28, s28] = request.security(u28, per, func(), ignore_invalid_symbol = true)
[v29, s29] = request.security(u29, per, func(), ignore_invalid_symbol = true)
[v30, s30] = request.security(u30, per, func(), ignore_invalid_symbol = true)
[v31, s31] = request.security(u31, per, func(), ignore_invalid_symbol = true)
[v32, s32] = request.security(u32, per, func(), ignore_invalid_symbol = true)
[v33, s33] = request.security(u33, per, func(), ignore_invalid_symbol = true)
[v34, s34] = request.security(u34, per, func(), ignore_invalid_symbol = true)
[v35, s35] = request.security(u35, per, func(), ignore_invalid_symbol = true)
[v36, s36] = request.security(u36, per, func(), ignore_invalid_symbol = true)
[v37, s37] = request.security(u37, per, func(), ignore_invalid_symbol = true)
[v38, s38] = request.security(u38, per, func(), ignore_invalid_symbol = true)
[v39, s39] = request.security(u39, per, func(), ignore_invalid_symbol = true)
[v40, s40] = request.security(u40, per, func(), ignore_invalid_symbol = true)

scr_label = 'TARAMA\n'
scr_label := bool(s1) ? scr_label + syminfo.ticker(u1) + ' ' + str.tostring(v1) + '\n' : scr_label
scr_label := bool(s2) ? scr_label + syminfo.ticker(u2) + ' ' + str.tostring(v2) + '\n' : scr_label
scr_label := bool(s3) ? scr_label + syminfo.ticker(u3) + ' ' + str.tostring(v3) + '\n' : scr_label
scr_label := bool(s4) ? scr_label + syminfo.ticker(u4) + ' ' + str.tostring(v4) + '\n' : scr_label
scr_label := bool(s5) ? scr_label + syminfo.ticker(u5) + ' ' + str.tostring(v5) + '\n' : scr_label
scr_label := bool(s6) ? scr_label + syminfo.ticker(u6) + ' ' + str.tostring(v6) + '\n' : scr_label
scr_label := bool(s7) ? scr_label + syminfo.ticker(u7) + ' ' + str.tostring(v7) + '\n' : scr_label
scr_label := bool(s8) ? scr_label + syminfo.ticker(u8) + ' ' + str.tostring(v8) + '\n' : scr_label
scr_label := bool(s9) ? scr_label + syminfo.ticker(u9) + ' ' + str.tostring(v9) + '\n' : scr_label
scr_label := bool(s10) ? scr_label + syminfo.ticker(u10) + ' ' + str.tostring(v10) + '\n' : scr_label
scr_label := bool(s11) ? scr_label + syminfo.ticker(u11) + ' ' + str.tostring(v11) + '\n' : scr_label
scr_label := bool(s12) ? scr_label + syminfo.ticker(u12) + ' ' + str.tostring(v12) + '\n' : scr_label
scr_label := bool(s13) ? scr_label + syminfo.ticker(u13) + ' ' + str.tostring(v13) + '\n' : scr_label
scr_label := bool(s14) ? scr_label + syminfo.ticker(u14) + ' ' + str.tostring(v14) + '\n' : scr_label
scr_label := bool(s15) ? scr_label + syminfo.ticker(u15) + ' ' + str.tostring(v15) + '\n' : scr_label
scr_label := bool(s16) ? scr_label + syminfo.ticker(u16) + ' ' + str.tostring(v16) + '\n' : scr_label
scr_label := bool(s17) ? scr_label + syminfo.ticker(u17) + ' ' + str.tostring(v17) + '\n' : scr_label
scr_label := bool(s18) ? scr_label + syminfo.ticker(u18) + ' ' + str.tostring(v18) + '\n' : scr_label
scr_label := bool(s19) ? scr_label + syminfo.ticker(u19) + ' ' + str.tostring(v19) + '\n' : scr_label
scr_label := bool(s20) ? scr_label + syminfo.ticker(u20) + ' ' + str.tostring(v20) + '\n' : scr_label
scr_label := bool(s21) ? scr_label + syminfo.ticker(u21) + ' ' + str.tostring(v21) + '\n' : scr_label
scr_label := bool(s22) ? scr_label + syminfo.ticker(u22) + ' ' + str.tostring(v22) + '\n' : scr_label
scr_label := bool(s23) ? scr_label + syminfo.ticker(u23) + ' ' + str.tostring(v23) + '\n' : scr_label
scr_label := bool(s24) ? scr_label + syminfo.ticker(u24) + ' ' + str.tostring(v24) + '\n' : scr_label
scr_label := bool(s25) ? scr_label + syminfo.ticker(u25) + ' ' + str.tostring(v25) + '\n' : scr_label
scr_label := bool(s26) ? scr_label + syminfo.ticker(u26) + ' ' + str.tostring(v26) + '\n' : scr_label
scr_label := bool(s27) ? scr_label + syminfo.ticker(u27) + ' ' + str.tostring(v27) + '\n' : scr_label
scr_label := bool(s28) ? scr_label + syminfo.ticker(u28) + ' ' + str.tostring(v28) + '\n' : scr_label
scr_label := bool(s29) ? scr_label + syminfo.ticker(u29) + ' ' + str.tostring(v29) + '\n' : scr_label
scr_label := bool(s30) ? scr_label + syminfo.ticker(u30) + ' ' + str.tostring(v30) + '\n' : scr_label
scr_label := bool(s31) ? scr_label + syminfo.ticker(u31) + ' ' + str.tostring(v31) + '\n' : scr_label
scr_label := bool(s32) ? scr_label + syminfo.ticker(u32) + ' ' + str.tostring(v32) + '\n' : scr_label
scr_label := bool(s33) ? scr_label + syminfo.ticker(u33) + ' ' + str.tostring(v33) + '\n' : scr_label
scr_label := bool(s34) ? scr_label + syminfo.ticker(u34) + ' ' + str.tostring(v34) + '\n' : scr_label
scr_label := bool(s35) ? scr_label + syminfo.ticker(u35) + ' ' + str.tostring(v35) + '\n' : scr_label
scr_label := bool(s36) ? scr_label + syminfo.ticker(u36) + ' ' + str.tostring(v36) + '\n' : scr_label
scr_label := bool(s37) ? scr_label + syminfo.ticker(u37) + ' ' + str.tostring(v37) + '\n' : scr_label
scr_label := bool(s38) ? scr_label + syminfo.ticker(u38) + ' ' + str.tostring(v38) + '\n' : scr_label
scr_label := bool(s39) ? scr_label + syminfo.ticker(u39) + ' ' + str.tostring(v39) + '\n' : scr_label
scr_label := bool(s40) ? scr_label + syminfo.ticker(u40) + ' ' + str.tostring(v40) + '\n' : scr_label

loc = input.int(defval = 10, title = 'Konum Ayarı', minval = -100, maxval = 100, step = 10, group = 'Tablonun konumunu belirler')
lab_1 = label.new(bar_index + loc, close, scr_label, color = color.green, textcolor = color.white, style = label.style_label_upper_left, size = size.normal)
label.delete(lab_1[1])


//////-------------------------------------------------------------------------------------------------------------
